[project]
name = "python-backend-playground"
version = "0.1.0"
description = "Python backend playground"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "pyright>=1.1.407",
    "ruff>=0.14.6",
]
